### PR TITLE
Shift FB Sourcing To JSON and update Collections in config.yaml

### LINKED ISSUE #4: Implement FB Data Sourcing
**Is your feature request related to a problem? Please describe.**
Currently, the site doesn't display Facebook event data, which is a particularly useful service for BEGIN users.

**Describe the solution you'd like**
Use the Facebook API along with Netlify Functions and the Github API to format and push Facebook event data to the repo.

**Describe alternatives you've considered**
We considered using `gatsby-source-facebook`, but this would result in the same issues described in #3 .

### PR DESCRIPTION
**Pull request by somaniarushi**
JSON sourcing with the data source, start time, name, description, location, and url in the CMS. Pushes alongside current time, and stores in `src/data/fb`

Fixes #4

### CODE REVIEW

**Comment by somaniarushi** [comment]
Note: Auto-deploys have failed due to lack of config.js in the github.

**Review by akirillo — CHANGES_REQUESTED** [review]
Great stuff! A couple of changes tho:
- `config.yml` (in the `facebook` collection)
  - The field labeled "Title" should have the `name` field set to "title" (this is an expected default)
  - Can you add a `page` field to store which FB page we pulled the event from ("string" `widget`)
  - Let's give the field labeled "Date" the name "date" (for consistency), and make its `widget` be a "datetime"
  - Let's set the `slug` to be `{{source}}-{{year}}-{{month}}-{{day}}` (also for consistency)
  - Let's set the "Description" field's `widget` to be "markdown"
- `source-fb.js`
  - Make the appropriate fixes to reflect the changes to `config.yml` above

**Comment by somaniarushi** [comment]
The reason I've made the slug more complicated is that there would be many events with the same date, and I'd rather not store them under the same name.

**Comment by somaniarushi** [comment]
I've made all the corrections except setting up a `page` widget –– this is because the Facebook API does not return a page name, only it's ID in the Facebook database (a 12-14 numbered key). Since I've set up batching, I can't match input to output either. My best idea right now is to set up another API call to get the master page of the event (maybe, I'm not sure –– I didn't see it in the events docs initially). I'll add an issue for it.

**Review by akirillo — APPROVED** [review]
Good point on the fact that multiple FB events will have the same date. Let's keep this slug structure for now, we may experiment with other categorization options in the future (e.g. one folder per FB page, etc.)

This looks great, though! I'll merge it in.
I'm also going to do a quick tweak to make the `date` field have a `datetime` widget, so don't let that throw you off.

**Pull request merged**
